import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";
import { BlurSection } from "@/widgets/BlurSection";

import "@/styles/globals.css";
import { ThemeProvider } from "@/widgets/providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className="dark:bg-dark-bg" style={GeistSans.style}>
        <ThemeProvider>
          <BlurSection />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
